package br.com.ricarlo.designsystem

import androidx.compose.ui.graphics.Color

/**
 * Light theme colors
 * */
internal val primaryLight = Color(0xFF4C662B)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFCDEDA3)
internal val onPrimaryContainerLight = Color(0xFF354E16)
internal val secondaryLight = Color(0xFF586249)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFDCE7C8)
internal val onSecondaryContainerLight = Color(0xFF404A33)
internal val tertiaryLight = Color(0xFF386663)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFBCECE7)
internal val onTertiaryContainerLight = Color(0xFF1F4E4B)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF93000A)
internal val backgroundLight = Color(0xFFF9FAEF)
internal val onBackgroundLight = Color(0xFF1A1C16)
internal val surfaceLight = Color(0xFFF9FAEF)
internal val onSurfaceLight = Color(0xFF1A1C16)
internal val surfaceVariantLight = Color(0xFFE1E4D5)
internal val onSurfaceVariantLight = Color(0xFF44483D)
internal val outlineLight = Color(0xFF75796C)
internal val outlineVariantLight = Color(0xFFC5C8BA)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF2F312A)
internal val inverseOnSurfaceLight = Color(0xFFF1F2E6)
internal val inversePrimaryLight = Color(0xFFB1D18A)
internal val surfaceDimLight = Color(0xFFDADBD0)
internal val surfaceBrightLight = Color(0xFFF9FAEF)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFF3F4E9)
internal val surfaceContainerLight = Color(0xFFEEEFE3)
internal val surfaceContainerHighLight = Color(0xFFE8E9DE)
internal val surfaceContainerHighestLight = Color(0xFFE2E3D8)

/**
 * Dark theme colors
 */
internal val primaryDark = Color(0xFFB1D18A)
internal val onPrimaryDark = Color(0xFF1F3701)
internal val primaryContainerDark = Color(0xFF354E16)
internal val onPrimaryContainerDark = Color(0xFFCDEDA3)
internal val secondaryDark = Color(0xFFBFCBAD)
internal val onSecondaryDark = Color(0xFF2A331E)
internal val secondaryContainerDark = Color(0xFF404A33)
internal val onSecondaryContainerDark = Color(0xFFDCE7C8)
internal val tertiaryDark = Color(0xFFA0D0CB)
internal val onTertiaryDark = Color(0xFF003735)
internal val tertiaryContainerDark = Color(0xFF1F4E4B)
internal val onTertiaryContainerDark = Color(0xFFBCECE7)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF12140E)
internal val onBackgroundDark = Color(0xFFE2E3D8)
internal val surfaceDark = Color(0xFF12140E)
internal val onSurfaceDark = Color(0xFFE2E3D8)
internal val surfaceVariantDark = Color(0xFF44483D)
internal val onSurfaceVariantDark = Color(0xFFC5C8BA)
internal val outlineDark = Color(0xFF8F9285)
internal val outlineVariantDark = Color(0xFF44483D)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFE2E3D8)
internal val inverseOnSurfaceDark = Color(0xFF2F312A)
internal val inversePrimaryDark = Color(0xFF4C662B)
internal val surfaceDimDark = Color(0xFF12140E)
internal val surfaceBrightDark = Color(0xFF383A32)
internal val surfaceContainerLowestDark = Color(0xFF0C0F09)
internal val surfaceContainerLowDark = Color(0xFF1A1C16)
internal val surfaceContainerDark = Color(0xFF1E201A)
internal val surfaceContainerHighDark = Color(0xFF282B24)
internal val surfaceContainerHighestDark = Color(0xFF33362E)
